### ISSUE TITLE
npm run serve fails

### ISSUE THREAD

**Issue by hwellmann** [TomWyllie/folkfriend#33]
```
hwellmann@josquin app % npm run serve

> folkfriend@3.3.0 serve /Users/hwellmann/git/folkfriend/app
> vue-cli-service serve

 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 error                                                                                                                   12:08:41

 error  in ./src/services/worker.js

Syntax Error: ChunkRenderError: Conflict: Multiple chunks emit assets to the same filename js/0.worker.js (chunks 0 and 0)


 @ ./src/services/backend.js 1:0-107
 @ ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.101:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

I'm not familiar with vue, and I have no clue what's wrong here...

**Comment by TomWyllie** [comment]
Thanks for filling this as an issue. I've had this problem for a while too and have been unable to figure out how to fix, but there is a quick workaround that I use when developing.

Run `npm run serve` and let it fail with the error you've described. Then, without cancelling that process, change the path of `./worker.js` at line of 20 `services/backend.js` to any non existent path, e.g. `./worker.js.foo` and save. The `npm run serve` error then changes to see it can't find the specified path to that file (obviously). Then change it back to the original `./worker.js` and the error should disappear and the app be served.

This is a dirty workaround but you leave the `serve` command running in the background then you only need to do this once per debugging session. `npm run build` is unaffected by this and so it's a development only issue. It's still annoying though - if you find a proper fix submit a PR!

**Comment by hwellmann** [comment]
Thanks for the quick reply, the workaround helps.

The `worker-plugin` README says that Webpack 5 can handle web workers out of the box, so I tried upgrading to Vue 5.x and Webpack 5.x which seems to solve the problem, at least the build completes without errors.

I'll submit a PR with that upgrade.

**Comment by TomWyllie** [comment]
https://github.com/TomWyllie/folkfriend/pull/35
